// Shared pantry configuration between client and server
export const PANTRY_ITEMS = {
  SPICES_AND_HERBS: [
    'salt',
    'black pepper',
    'pepper',
    'oregano',
    'basil',
    'thyme',
    'paprika',
    'cumin',
    'cinnamon',
    'nutmeg',
    'garlic powder',
    'onion powder',
    'chili powder',
    'red pepper flakes',
    'bay leaves',
    'sage',
    'rosemary',
    'turmeric',
    'ginger powder',
    'allspice',
    'cilantro',
    'dill',
    'parsley',
    'mint',
    'curry powder',
    'italian seasoning',
    'italian herbs',
    'herbs de provence',
    'poultry seasoning',
    'pumpkin pie spice',
    'chinese five spice',
    'garam masala',
    'cardamom',
    'coriander',
    'fennel',
    'marjoram',
    'tarragon'
  ],
  BAKING: [
    'all purpose flour',
    'bread flour',
    'cake flour',
    'white flour',
    'granulated sugar',
    'white sugar',
    'brown sugar',
    'powdered sugar',
    'confectioners sugar',
    'baking powder',
    'baking soda',
    'cornstarch',
    'vanilla extract',
    'pure vanilla extract',
    'active dry yeast',
    'instant yeast',
    'cocoa powder',
    'unsweetened cocoa powder'
  ],
  OILS_AND_VINEGARS: [
    'olive oil',
    'vegetable oil',
    'canola oil',
    'coconut oil',
    'sesame oil',
    'cooking spray',
    'white vinegar',
    'balsamic vinegar',
    'apple cider vinegar',
    'rice vinegar'
  ],
  CONDIMENTS: [
    'soy sauce',
    'mustard',
    'mayonnaise',
    'ketchup',
    'hot sauce',
    'worcestershire sauce',
    'fish sauce',
    'oyster sauce',
    'hoisin sauce',
    'sriracha',
    'tabasco'
  ],
  CANNED_AND_JARRED: [
    'tomato paste',
    'tomato sauce',
    'diced tomatoes',
    'crushed tomatoes',
    'canned black beans',
    'canned kidney beans',
    'canned chickpeas',
    'canned garbanzo beans',
    'coconut milk',
    'broth',
    'stock',
    'bouillon'
  ],
  GRAINS_AND_PASTA: [
    'white rice',
    'brown rice',
    'quinoa',
    'pasta',
    'spaghetti',
    'penne',
    'fettuccine',
    'bread crumbs',
    'panko',
    'oats',
    'cornmeal',
    'couscous'
  ]
};

// Additional categories for fresh/perishable items
export const FRESH_CATEGORIES = {
  PRODUCE: [
    'tomato',
    'onion',
    'garlic',
    'lettuce',
    'cucumber',
    'avocado',
    'lemon',
    'lime',
    'carrot',
    'celery',
    'potato',
    'bell pepper',
    'spinach',
    'kale',
    'broccoli',
    'cauliflower',
    'mushroom',
    'zucchini',
    'squash',
    'eggplant',
    'asparagus',
    'green beans',
    'peas',
    'corn',
    'sweet potato',
    'ginger root',
    'herbs'
  ],
  MEAT_AND_POULTRY: [
    'chicken',
    'beef',
    'pork',
    'turkey',
    'lamb',
    'sausage',
    'bacon',
    'ham',
    'ground',
    'thighs',
    'breast',
    'wings',
    'drumsticks',
    'steak',
    'roast',
    'chops'
  ],
  DAIRY_AND_EGGS: [
    'milk',
    'cream',
    'half and half',
    'cheese',
    'yogurt',
    'butter',
    'egg',
    'eggs',
    'feta',
    'mozzarella',
    'parmesan',
    'cheddar',
    'cottage cheese',
    'sour cream',
    'cream cheese'
  ],
  SEAFOOD: [
    'fish',
    'salmon',
    'tuna',
    'shrimp',
    'cod',
    'tilapia',
    'halibut',
    'crab',
    'lobster',
    'scallops',
    'mussels',
    'clams'
  ],
  FROZEN: [
    'frozen',
    'ice cream',
    'frozen vegetables',
    'frozen fruit',
    'frozen pizza',
    'frozen meals'
  ]
};

export const DEFAULT_PANTRY_SETTINGS = {
  includePantryItems: false,  // By default, exclude pantry items
  customPantryItems: [],      // User can add their own pantry items
  excludedCategories: [],     // User can exclude entire categories
  minimumQuantity: {          // Only add to cart if below these amounts
    SPICES_AND_HERBS: '1 oz',
    OILS_AND_VINEGARS: '8 oz',
    CONDIMENTS: '4 oz',
    CANNED_AND_JARRED: '1 can',
    GRAINS_AND_PASTA: '1 lb'
  }
}; 